table Consolidado_Abono_ATUAL
	lineageTag: a36543a5-20f2-42b4-b4e5-21151ed942d7

	column 'Nome da Origem'
		dataType: string
		lineageTag: cc2c6be6-f6d7-4159-8f86-6f3de005ad81
		summarizeBy: none
		sourceColumn: Nome da Origem

		annotation SummarizationSetBy = Automatic

	column 'ID Cliente'
		dataType: string
		lineageTag: ed7a455f-9859-4a11-b98c-f9744086ba36
		summarizeBy: none
		sourceColumn: ID Cliente

		annotation SummarizationSetBy = Automatic

	column 'Número WorFinity'
		dataType: string
		lineageTag: 5d46b16f-802c-4cdb-82d7-6fd8e0031b71
		summarizeBy: none
		sourceColumn: Número WorFinity

		annotation SummarizationSetBy = Automatic

	column Polo
		dataType: string
		lineageTag: 6e77bf9c-c394-4d69-bb42-8d4efad8de6c
		summarizeBy: none
		sourceColumn: Polo

		annotation SummarizationSetBy = Automatic

	column Técnico
		dataType: string
		lineageTag: 074bc157-529d-4660-acbc-8761c38f88ff
		summarizeBy: none
		sourceColumn: Técnico

		annotation SummarizationSetBy = Automatic

	column 'Novo Modelo'
		dataType: string
		lineageTag: 72bbb043-e90b-4a81-a48e-4011da406f51
		summarizeBy: none
		sourceColumn: Novo Modelo

		annotation SummarizationSetBy = Automatic

	column 'Data e Hora Abertura'
		dataType: string
		lineageTag: 70a5ef8b-cf3d-43d5-b7b6-cf59ed83c59f
		summarizeBy: none
		sourceColumn: Data e Hora Abertura

		annotation SummarizationSetBy = Automatic

	column 'Data Limite Atendimento'
		dataType: string
		lineageTag: 7fa1dadc-8cb5-494f-8140-16f5eb26a61b
		summarizeBy: none
		sourceColumn: Data Limite Atendimento

		annotation SummarizationSetBy = Automatic

	column 'Fechamento OS'
		dataType: dateTime
		formatString: General Date
		lineageTag: 372619d3-6c13-4d4f-8f28-78d649834fa5
		summarizeBy: none
		sourceColumn: Fechamento OS

		variation Variation
			isDefault
			relationship: 7e9582e0-d78d-4ea7-b304-b6137521f744
			defaultHierarchy: LocalDateTable_bb7b3549-a21e-4f4e-977f-578ab2425cb8.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

	column 'Está no Prazo?'
		dataType: string
		lineageTag: 3679f96f-cc92-4942-aa98-184868c633f6
		summarizeBy: none
		sourceColumn: Está no Prazo?

		annotation SummarizationSetBy = Automatic

	column 'Status Serial'
		dataType: string
		lineageTag: 6f9b8e8a-8623-4359-b74b-5fbb17d5e6f3
		summarizeBy: none
		sourceColumn: Status Serial

		annotation SummarizationSetBy = Automatic

	column 'Tipo de Serviço'
		dataType: string
		lineageTag: 32d3f77a-4fda-4d82-84ab-791c24d7cb26
		summarizeBy: none
		sourceColumn: Tipo de Serviço

		annotation SummarizationSetBy = Automatic

	column Família
		dataType: string
		lineageTag: 09c2174c-0cee-4413-bf98-726c71e342a0
		summarizeBy: none
		sourceColumn: Família

		annotation SummarizationSetBy = Automatic

	column 'Lead Time Dias Ùteis'
		dataType: string
		lineageTag: fdf9b1a7-60be-4a1b-bcd6-a0e7e7dc37d8
		summarizeBy: none
		sourceColumn: Lead Time Dias Ùteis

		annotation SummarizationSetBy = Automatic

	column cep
		dataType: string
		lineageTag: ae3b5bd9-e7d5-4a14-af2e-b8a388bedf5b
		summarizeBy: none
		sourceColumn: cep

		annotation SummarizationSetBy = Automatic

	column estado
		dataType: string
		lineageTag: 1c489f37-b963-4008-ba5e-d1c051a24324
		summarizeBy: none
		sourceColumn: estado

		annotation SummarizationSetBy = Automatic

	column recebedor
		dataType: string
		lineageTag: ccf78732-2569-4d48-ba32-d82e9970c366
		summarizeBy: none
		sourceColumn: recebedor

		annotation SummarizationSetBy = Automatic

	column cidade
		dataType: string
		lineageTag: 1d22f30f-d4ff-4f4f-8447-e1038437dba9
		summarizeBy: none
		sourceColumn: cidade

		annotation SummarizationSetBy = Automatic

	column MesRef
		dataType: string
		lineageTag: b911f9f7-b1cd-474b-b999-ffaee3e27cd6
		summarizeBy: none
		sourceColumn: MesRef

		annotation SummarizationSetBy = Automatic

	column Data_Snapshot
		dataType: dateTime
		formatString: Long Date
		lineageTag: dc027ebd-6b9c-4a47-8520-cfc05008e771
		summarizeBy: none
		sourceColumn: Data_Snapshot

		variation Variation
			isDefault
			relationship: 8ff1a34f-0a18-4309-9023-f40529a0536c
			defaultHierarchy: LocalDateTable_e0e1af73-6d08-46eb-a998-7e9849e7e12f.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column OS_ID
		dataType: string
		lineageTag: 8e7de8a0-a037-4e2c-88a3-fad133fc934a
		summarizeBy: none
		sourceColumn: OS_ID

		annotation SummarizationSetBy = Automatic

	column FechamentoOS_Date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 651acff5-faba-4f61-b911-88e1f9dc34a8
		summarizeBy: none
		sourceColumn: FechamentoOS_Date

		variation Variation
			isDefault
			relationship: 66a12154-8e28-4efa-967a-16ac5b804ae0
			defaultHierarchy: LocalDateTable_e3dea9e1-cb05-4de0-a797-fc0b693d0238.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Status_Prazo_Original
		dataType: string
		lineageTag: a61c5cd5-d586-4492-9b3a-cdd42d7adbc4
		summarizeBy: none
		sourceColumn: Status_Prazo_Original

		annotation SummarizationSetBy = Automatic

	column Data_Fechamento_Limpa
		dataType: dateTime
		formatString: Long Date
		lineageTag: c457a945-e1d9-455f-9bb4-d49d9a3f9c2c
		summarizeBy: none
		sourceColumn: Data_Fechamento_Limpa

		variation Variation
			isDefault
			relationship: 02580548-131e-49c8-b929-3975d8321e80
			defaultHierarchy: LocalDateTable_087a4af0-5be3-4a89-b07e-ee14e4966053.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Data_SLA
		dataType: dateTime
		formatString: Long Date
		lineageTag: 28c919cd-8afd-4d40-9f67-15f967e5adbf
		summarizeBy: none
		sourceColumn: Data_SLA

		variation Variation
			isDefault
			relationship: 27151215-c2d4-4c82-a0ad-48721876c10a
			defaultHierarchy: LocalDateTable_ec6af7e2-c1c2-49de-884b-8aef70e09042.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Status da Justificativa'
		dataType: string
		lineageTag: 904ae1b6-b912-4608-81ae-6c95e6f2e3ff
		summarizeBy: none
		sourceColumn: Status da Justificativa

		annotation SummarizationSetBy = Automatic

	column 'Status do Abono'
		dataType: string
		lineageTag: 1989a330-eaf0-4e2e-bcb3-6fe27bd68aca
		summarizeBy: none
		sourceColumn: Status do Abono

		annotation SummarizationSetBy = Automatic

	column Observação
		dataType: string
		lineageTag: ad72e9c2-e86c-44b2-8fea-5b2673b42a37
		summarizeBy: none
		sourceColumn: Observação

		annotation SummarizationSetBy = Automatic

	column 'Justificativa do Prestador'
		dataType: string
		lineageTag: eea38a26-e301-4d6c-9662-ffb62c396ba9
		summarizeBy: none
		sourceColumn: Justificativa do Prestador

		annotation SummarizationSetBy = Automatic

	column RET_WF_Just_Prest
		dataType: string
		lineageTag: 45e6e356-9c41-4f1a-8628-a76fb94803b0
		summarizeBy: none
		sourceColumn: RET_WF_Just_Prest

		annotation SummarizationSetBy = Automatic

	column RET_WF_Observacao
		dataType: string
		lineageTag: 47ee8711-0f1c-4e20-aed0-af47e2889b87
		summarizeBy: none
		sourceColumn: RET_WF_Observacao

		annotation SummarizationSetBy = Automatic

	column RET_WF_Abono
		dataType: string
		lineageTag: bdd463af-1d3d-4223-b2e6-ecf14bb5bc18
		summarizeBy: none
		sourceColumn: RET_WF_Abono

		annotation SummarizationSetBy = Automatic

	column WF_Abono
		dataType: string
		lineageTag: d6675df6-a639-49f3-a84a-bdb3460a4f7c
		summarizeBy: none
		sourceColumn: WF_Abono

		annotation SummarizationSetBy = Automatic

	column WF_Just_Prest
		dataType: string
		lineageTag: 194bb7b7-ab23-4cb3-a9e7-89ad8df617a4
		summarizeBy: none
		sourceColumn: WF_Just_Prest

		annotation SummarizationSetBy = Automatic

	column WF_Observacao
		dataType: string
		lineageTag: b3f6c6f5-702e-4b3d-b037-ce655432de24
		summarizeBy: none
		sourceColumn: WF_Observacao

		annotation SummarizationSetBy = Automatic

	column Fonte
		dataType: string
		lineageTag: d905fec7-6909-4708-84d7-45be79dc6305
		summarizeBy: none
		sourceColumn: Fonte

		annotation SummarizationSetBy = Automatic

	column Status_Abono
		dataType: string
		lineageTag: b9caf757-0207-4b92-a154-4b5dd3b91bd1
		summarizeBy: none
		sourceColumn: Status_Abono

		annotation SummarizationSetBy = Automatic

	column WF_Abono_Flag
		dataType: int64
		formatString: 0
		lineageTag: 0eca186b-354f-432d-9f63-5693f03284f4
		summarizeBy: sum
		sourceColumn: WF_Abono_Flag

		annotation SummarizationSetBy = Automatic

	column Cod_Polo
		dataType: string
		lineageTag: 04a3420b-923e-401d-80e4-460237a6884f
		summarizeBy: none
		sourceColumn: Cod_Polo

		annotation SummarizationSetBy = Automatic

	partition Consolidado_Abono_ATUAL = m
		mode: import
		source =
				let
				    Fonte = Folder.Files("C:\Users\sbahia\OneDrive - UNIVERSO ONLINE S.A\Área de Trabalho\Ambiente PY\logins\Dash Fifo\Dados Mensais\ATUAL"),
				    #"Linhas Filtradas" = Table.SelectRows(Fonte, each Text.Contains([Name], "Analítico de OS's Finalizadas")),
				    #"Arquivos Ocultos Filtrados1" = Table.SelectRows(#"Linhas Filtradas", each [Attributes]?[Hidden]? <> true),
				    #"Invocar Função Personalizada1" = Table.AddColumn(#"Arquivos Ocultos Filtrados1", "Transformar Arquivo", each #"Transformar Arquivo"([Content])),
				    #"Colunas Renomeadas1" = Table.RenameColumns(#"Invocar Função Personalizada1", {"Name", "Nome da Origem"}),
				    #"Outras Colunas Removidas1" = Table.SelectColumns(#"Colunas Renomeadas1", {"Nome da Origem", "Transformar Arquivo"}),
				
				    // EXPANSÃO: une colunas de todos os arquivos (inclui as do mês 10)
				    ColunasModelo =
				        let
				            tabelas = #"Outras Colunas Removidas1"[Transformar Arquivo],
				            listas  = List.Transform(tabelas, each try Table.ColumnNames(_) otherwise {}),
				            uniao   = List.Distinct(List.Combine(listas))
				        in
				            uniao,
				    #"Coluna de Tabela Expandida1" = Table.ExpandTableColumn(#"Outras Colunas Removidas1", "Transformar Arquivo", ColunasModelo, ColunasModelo),
				
				    // normalização mínima (renomeia só se destino não existir)
				    MapCols = {
				        {"Cidade","cidade"},
				        {"CEP","cep"},
				        {"Cep","cep"},
				        {"Estado","estado"},
				        {"Recebedor","recebedor"},
				        {"Está no Prazo","Está no Prazo?"},
				        {"Esta no Prazo","Está no Prazo?"},
				        {"Tipo de Visita","Tipo de Serviço"},
				        {"Familia","Família"},
				        {"Lead Time Dias Úteis","Lead Time Dias Ùteis"},
				        {"Lead Time Dias Uteis","Lead Time Dias Ùteis"}
				    },
				    Normalizado =
				        List.Accumulate(
				            MapCols,
				            #"Coluna de Tabela Expandida1",
				            (t,p) =>
				                let
				                    src  = p{0},
				                    dst  = p{1},
				                    cols = Table.ColumnNames(t)
				                in
				                    if List.Contains(cols, src) and not List.Contains(cols, dst)
				                    then Table.RenameColumns(t,{p}, MissingField.Ignore)
				                    else t
				        ),
				
				    // Tipo de Serviço <- (Tipo de Serviço | Tipo de Visita)
				    _TipoServ_add = Table.AddColumn(
				        Normalizado,
				        "_TipoServ_tmp",
				        each
				            let
				                a = try Text.Trim(Text.From(Record.Field(_, "Tipo de Serviço"))) otherwise null,
				                b = try Text.Trim(Text.From(Record.Field(_, "Tipo de Visita")))   otherwise null
				            in
				                if a <> null and a <> "" then a else b,
				        type text
				    ),
				    _TipoServ_drop = Table.RemoveColumns(_TipoServ_add, {"Tipo de Serviço"}, MissingField.Ignore),
				    _TipoServ_set  = Table.RenameColumns(_TipoServ_drop, {{"_TipoServ_tmp","Tipo de Serviço"}}, MissingField.Ignore),
				
				    // Família <- (Família | Familia)
				    _Familia_add = Table.AddColumn(
				        _TipoServ_set,
				        "_Familia_tmp",
				        each
				            let
				                a = try Text.Trim(Text.From(Record.Field(_, "Família"))) otherwise null,
				                b = try Text.Trim(Text.From(Record.Field(_, "Familia")))  otherwise null
				            in
				                if a <> null and a <> "" then a else b,
				        type text
				    ),
				    _Familia_drop = Table.RemoveColumns(_Familia_add, {"Família"}, MissingField.Ignore),
				    _Familia_set  = Table.RenameColumns(_Familia_drop, {{"_Familia_tmp","Família"}}, MissingField.Ignore),
				
				    // Lead Time Dias Ùteis <- (Lead Time Dias Ùteis | Lead Time Dias Úteis | Lead Time Dias Uteis)
				    _LT_add = Table.AddColumn(
				        _Familia_set,
				        "_LT_tmp",
				        each
				            let
				                a = try Text.Trim(Text.From(Record.Field(_, "Lead Time Dias Ùteis"))) otherwise null,
				                b = try Text.Trim(Text.From(Record.Field(_, "Lead Time Dias Úteis"))) otherwise null,
				                c = try Text.Trim(Text.From(Record.Field(_, "Lead Time Dias Uteis"))) otherwise null
				            in
				                List.First(
				                    List.RemoveNulls({
				                        if a = "" then null else a,
				                        if b = "" then null else b,
				                        if c = "" then null else c
				                    }),
				                    null
				                ),
				        type text
				    ),
				    _LT_drop = Table.RemoveColumns(_LT_add, {"Lead Time Dias Ùteis"}, MissingField.Ignore),
				    _LT_set  = Table.RenameColumns(_LT_drop, {{"_LT_tmp","Lead Time Dias Ùteis"}}, MissingField.Ignore),
				
				    // cep <- (cep | CEP | Cep)
				    _cep_add = Table.AddColumn(
				        _LT_set,
				        "_cep_tmp",
				        each
				            let
				                a = try Text.Trim(Text.From(Record.Field(_, "cep"))) otherwise null,
				                b = try Text.Trim(Text.From(Record.Field(_, "CEP"))) otherwise null,
				                c = try Text.Trim(Text.From(Record.Field(_, "Cep"))) otherwise null
				            in
				                List.First(
				                    List.RemoveNulls({
				                        if a = "" then null else a,
				                        if b = "" then null else b,
				                        if c = "" then null else c
				                    }),
				                    null
				                ),
				        type text
				    ),
				    _cep_drop = Table.RemoveColumns(_cep_add, {"cep"}, MissingField.Ignore),
				    _cep_set  = Table.RenameColumns(_cep_drop, {{"_cep_tmp","cep"}}, MissingField.Ignore),
				
				    // estado <- (estado | Estado)
				    _estado_add = Table.AddColumn(
				        _cep_set,
				        "_estado_tmp",
				        each
				            let
				                a = try Text.Trim(Text.From(Record.Field(_, "estado"))) otherwise null,
				                b = try Text.Trim(Text.From(Record.Field(_, "Estado"))) otherwise null
				            in
				                if a <> null and a <> "" then a else b,
				        type text
				    ),
				    _estado_drop = Table.RemoveColumns(_estado_add, {"estado"}, MissingField.Ignore),
				    _estado_set  = Table.RenameColumns(_estado_drop, {{"_estado_tmp","estado"}}, MissingField.Ignore),
				
				    // recebedor <- (recebedor | Recebedor)
				    _receb_add = Table.AddColumn(
				        _estado_set,
				        "_receb_tmp",
				        each
				            let
				                a = try Text.Trim(Text.From(Record.Field(_, "recebedor"))) otherwise null,
				                b = try Text.Trim(Text.From(Record.Field(_, "Recebedor"))) otherwise null
				            in
				                if a <> null and a <> "" then a else b,
				        type text
				    ),
				    _receb_drop = Table.RemoveColumns(_receb_add, {"recebedor"}, MissingField.Ignore),
				    _receb_set  = Table.RenameColumns(_receb_drop, {{"_receb_tmp","recebedor"}}, MissingField.Ignore),
				
				    // cidade <- (cidade | Cidade)
				    _cidade_add = Table.AddColumn(
				        _receb_set,
				        "_cidade_tmp",
				        each
				            let
				                a = try Text.Trim(Text.From(Record.Field(_, "cidade"))) otherwise null,
				                b = try Text.Trim(Text.From(Record.Field(_, "Cidade"))) otherwise null
				            in
				                if a <> null and a <> "" then a else b,
				        type text
				    ),
				    _cidade_drop = Table.RemoveColumns(_cidade_add, {"cidade"}, MissingField.Ignore),
				    Preenchido   = Table.RenameColumns(_cidade_drop, {{"_cidade_tmp","cidade"}}, MissingField.Ignore),
				
				    // mantém linhas com OS
				    #"Remover Linhas Vazias" =
				        Table.SelectRows(
				            Preenchido,
				            each [Número WorFinity] <> null and Text.Trim(Text.From([Número WorFinity])) <> ""
				        ),
				
				    // snapshot e chaves
				    #"Personalização Adicionada" =
				        Table.AddColumn(
				            #"Remover Linhas Vazias",
				            "MesRef",
				            each Text.Range([Nome da Origem], Text.PositionOf([Nome da Origem], "2025-"), 7)
				        ),
				    #"Data Snapshot" =
				        Table.AddColumn(
				            #"Personalização Adicionada",
				            "Data_Snapshot",
				            each if [MesRef] <> null then Date.EndOfMonth(Date.FromText([MesRef] & "-01")) else null,
				            type date
				        ),
				    #"Personalização Adicionada1" =
				        Table.AddColumn(
				            #"Data Snapshot",
				            "OS_ID",
				            each Text.Trim(Text.From([Número WorFinity]))
				        ),
				    #"Tipo Alterado3" =
				        Table.TransformColumnTypes(
				            #"Personalização Adicionada1",
				            {{"OS_ID", type text}, {"Fechamento OS", type datetime}}
				        ),
				
				    // data real de fechamento
				    #"FechamentoOS_Date" =
				        Table.AddColumn(
				            #"Tipo Alterado3",
				            "FechamentoOS_Date",
				            each if [Fechamento OS] <> null then Date.From([Fechamento OS]) else null,
				            type date
				        ),
				
				    // guarda status original de prazo (antes de padronizar)
				    #"Status Prazo Original" =
				        if List.Contains(Table.ColumnNames(#"FechamentoOS_Date"), "Está no Prazo?")
				        then
				            Table.AddColumn(
				                #"FechamentoOS_Date",
				                "Status_Prazo_Original",
				                each Text.Trim(Text.From([#"Está no Prazo?"])),
				                type text
				            )
				        else
				            #"FechamentoOS_Date",
				
				    // padroniza valores do prazo (mantido para não quebrar medidas existentes)
				    PrazoPadronizado =
				        if List.Contains(Table.ColumnNames(#"Status Prazo Original"), "Está no Prazo?")
				        then
				            Table.TransformColumns(
				                #"Status Prazo Original",
				                {{"Está no Prazo?",
				                  each let v = Text.Lower(Text.Trim(Text.From(_)))
				                       in  if v = "fechada dentro do prazo" or v = "dentro do prazo" then "Dentro do prazo"
				                           else if v = "fechada fora do prazo" or v = "fora do prazo" then "Fora do prazo"
				                           else _,
				                  type text}}
				            )
				        else
				            #"Status Prazo Original",
				
				    // fallback (não usar no slicer)
				    #"Data_Fechamento_Limpa" =
				        Table.AddColumn(
				            PrazoPadronizado,
				            "Data_Fechamento_Limpa",
				            each if [Fechamento OS] <> null then Date.From([Fechamento OS]) else [Data_Snapshot],
				            type date
				        ),
				
				    // Data_SLA: fechadas usam FechamentoOS_Date; abertas fora do prazo usam Data Limite Atendimento
				    #"Data SLA" =
				        Table.AddColumn(
				            #"Data_Fechamento_Limpa",
				            "Data_SLA",
				            each
				                let
				                    statusOrig =
				                        try Text.Lower(Text.Trim(Text.From([Status_Prazo_Original])))
				                        otherwise null,
				                    temFech = [FechamentoOS_Date] <> null,
				                    foraPrazo = statusOrig <> null and Text.Contains(statusOrig, "fora do prazo"),
				                    dataLimite =
				                        try Date.From([Data Limite Atendimento]) otherwise
				                        try Date.From([#"Data Limite Atendimento"]) otherwise null
				                in
				                    if temFech then [FechamentoOS_Date]
				                    else if foraPrazo then dataLimite
				                    else null,
				            type date
				        ),
				
				    // join justificativa
				    JoinJust =
				        Table.NestedJoin(
				            #"Data SLA",
				            {"OS_ID"},
				            Justificativa_Consolidada,
				            {"OS_ID"},
				            "Just",
				            JoinKind.LeftOuter
				        ),
				    ExpJust =
				        Table.ExpandTableColumn(
				            JoinJust,
				            "Just",
				            {"Status da Justificativa","Status do Abono","Observação","Justificativa do Prestador"},
				            {"Status da Justificativa","Status do Abono","Observação","Justificativa do Prestador"}
				        ),
				
				    // join retorno
				    JoinRet =
				        Table.NestedJoin(
				            ExpJust,
				            {"OS_ID"},
				            Retorno_Consolidado,
				            {"OS_ID"},
				            "Ret",
				            JoinKind.LeftOuter
				        ),
				    ExpRet =
				        Table.ExpandTableColumn(
				            JoinRet,
				            "Ret",
				            {"WF_Just_Prest","WF_Observacao","WF_Abono"},
				            {"RET_WF_Just_Prest","RET_WF_Observacao","RET_WF_Abono"}
				        ),
				
				    // campos WF finais
				    WF_Abono =
				        Table.AddColumn(
				            ExpRet,
				            "WF_Abono",
				            each
				                if [RET_WF_Abono] <> null and Text.Trim([RET_WF_Abono]) <> ""
				                then [RET_WF_Abono]
				                else [Status do Abono],
				            type text
				        ),
				    WF_Just_Prest =
				        Table.AddColumn(
				            WF_Abono,
				            "WF_Just_Prest",
				            each
				                if [RET_WF_Just_Prest] <> null and Text.Trim([RET_WF_Just_Prest]) <> ""
				                then [RET_WF_Just_Prest]
				                else [Justificativa do Prestador],
				            type text
				        ),
				    WF_Observacao =
				        Table.AddColumn(
				            WF_Just_Prest,
				            "WF_Observacao",
				            each
				                if [RET_WF_Observacao] <> null and Text.Trim([RET_WF_Observacao]) <> ""
				                then [RET_WF_Observacao]
				                else [Observação],
				            type text
				        ),
				
				    // FONTE: considera Workfinity só se tiver dado vindo de Justificativa/Retorno
				    FonteCorrigida =
				        Table.AddColumn(
				            WF_Observacao,
				            "Fonte",
				            each
				                let
				                    vJust   = try Text.Trim(Text.From([Status da Justificativa])) otherwise null,
				                    vAbRet  = try Text.Trim(Text.From([RET_WF_Abono]))          otherwise null,
				                    vJustR  = try Text.Trim(Text.From([RET_WF_Just_Prest]))     otherwise null,
				                    vObsRet = try Text.Trim(Text.From([RET_WF_Observacao]))     otherwise null
				                in
				                    if (vJust   <> null and vJust   <> "")
				                    or (vAbRet  <> null and vAbRet  <> "")
				                    or (vJustR  <> null and vJustR  <> "")
				                    or (vObsRet <> null and vObsRet <> "")
				                    then "Workfinity"
				                    else "Somente BI",
				            type text
				        ),
				
				    // status do abono
				    StatusAbono =
				        Table.AddColumn(
				            FonteCorrigida,
				            "Status_Abono",
				            each
				                if [#"Está no Prazo?"] = "Dentro do prazo" then null
				                else if [Fonte] = "Somente BI" then "Somente BI"
				                else if [WF_Abono] <> null and Text.Trim([WF_Abono]) <> "" then "Abonada"
				                else "Pendente de Abono",
				            type text
				        ),
				
				    // flags e chaves
				    #"Abono Flag" =
				        Table.AddColumn(
				            StatusAbono,
				            "WF_Abono_Flag",
				            each if [WF_Abono] <> null and Text.Trim([WF_Abono]) <> "" then 1 else 0,
				            Int64.Type
				        ),
				    #"Cod Polo" =
				        Table.AddColumn(
				            #"Abono Flag",
				            "Cod_Polo",
				            each Text.AfterDelimiter([Polo], "- ", {0, RelativePosition.FromEnd}),
				            type text
				        ),
				    #"Linhas Filtradas1" = Table.SelectRows(#"Cod Polo", each true)
				in
				    #"Linhas Filtradas1"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

