table FactOS
	excludeFromModelRefresh
	lineageTag: c029690e-8b18-46b7-aeaa-9bb8e784298e

	measure 'SLA_% Base' =
			
			AVERAGE(FactOS[pct_ordens_dentro_do_prazo_calculado])
		formatString: 0
		lineageTag: 4675d86d-1ac2-4977-9b4a-f77bb3f10937

	measure 'Ativacao_% Base' = ```
			
			CALCULATE(
			    AVERAGE(FactOS[pct_ordens_com_ativacao]),
			    FILTER(
			        ALL(FactOS[motivo_saida]),
			        LOWER(TRIM(FactOS[motivo_saida])) IN {
			            "adesão",
			            "atendimento expresso",
			            "instalação comodato"
			    
			        }
			    )
			)
			```
		lineageTag: 7fef8bc0-2d80-4161-b8a4-369fd6826bd6

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure CSAT_Base = AVERAGE(FactCSAT[nota_pesquisa])
		lineageTag: 953ae544-62cb-49a6-b432-1ed75763d92c

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'SLA_Qtd Dentro do Prazo Base' = ```
			
			SUM(FactOS[qtd_ordens_dentro_do_prazo_calculado])
			
			```
		formatString: 0
		lineageTag: f05a73f9-cbdb-4c1a-a184-80ed6d4e2c74

	measure 'Ativacao_Qtd Base' = ```
			
			SUM(FactOS[qtd_ativacoes])
			
			```
		formatString: 0
		lineageTag: 4e1cbd5f-29ec-4e17-862c-a1bfa089a008

	measure 'CSAT Médio Base (Considerar)' =
			
			CALCULATE(
			    AVERAGE(FactCSAT[nota_pesquisa]),
			    KEEPFILTERS( FactCSAT[STATUS] = "Considerar" )
			)
		lineageTag: fedaabde-e729-450a-a90d-6874ad2817b3

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'SLA_% (Regra Cargo)' =
			
			VAR CargoSel     = SELECTEDVALUE(Eixo_Colaboradores[Cargo])
			VAR CargoSelNorm0= UPPER(TRIM(CargoSel))
			VAR CargoSelNorm =
			    SUBSTITUTE(
			    SUBSTITUTE(
			    SUBSTITUTE(
			    SUBSTITUTE(
			    SUBSTITUTE(
			    SUBSTITUTE(
			    SUBSTITUTE(
			    SUBSTITUTE(
			    SUBSTITUTE(
			    SUBSTITUTE(
			    SUBSTITUTE(
			    SUBSTITUTE(CargoSelNorm0,"Á","A"),"À","A"),"Â","A"),"Ã","A"),"É","E"),
			    "Ê","E"),"Í","I"),"Ó","O"),"Ô","O"),"Õ","O"),"Ú","U"),"Ü","U")
			VAR PoloRegra    = SELECTEDVALUE(Eixo_Colaboradores[Polo Base (Regra)])
			VAR MatriculaSel = SELECTEDVALUE(Eixo_Colaboradores[Matricula])
			VAR MatSelTxt    = FORMAT(MatriculaSel, "")
			VAR NomeNormSel  = SELECTEDVALUE(Eixo_Colaboradores[Nome_Normalizado])
			VAR IsMatrizSel  = COALESCE(SELECTEDVALUE(Eixo_Colaboradores[IsMatriz]), FALSE())
			
			VAR IsLinha =
			    HASONEVALUE(Eixo_Colaboradores[Nome_Normalizado]) ||
			    HASONEVALUE(Eixo_Colaboradores[Matricula])
			
			VAR Polos_Lider =
			    CALCULATETABLE(
			        DISTINCT(FactOS[des_service_provider]),
			        KEEPFILTERS(
			            FILTER(
			                ALL(FactOS[Líder]),
			                VAR n  = UPPER(TRIM(FactOS[Líder]))
			                VAR n1 = SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(n,
			                       "Á","A"),"À","A"),"Â","A"),"Ã","A"),"É","E"),"Ê","E"),"Í","I"),"Ó","O"),"Ô","O"),"Õ","O")
			                VAR n2 = SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(n1,"Ú","U"),"Ü","U"),"Ç","C")
			                RETURN n2 = NomeNormSel
			            )
			        )
			    )
			VAR Polos_Coord =
			    CALCULATETABLE(
			        DISTINCT(FactOS[des_service_provider]),
			        KEEPFILTERS(
			            FILTER(
			                ALL(FactOS[Coordenador.Coordenador]),
			                VAR n  = UPPER(TRIM(FactOS[Coordenador.Coordenador]))
			                VAR n1 = SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(n,
			                       "Á","A"),"À","A"),"Â","A"),"Ã","A"),"É","E"),"Ê","E"),"Í","I"),"Ó","O"),"Ô","O"),"Õ","O")
			                VAR n2 = SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(n1,"Ú","U"),"Ü","U"),"Ç","C")
			                RETURN n2 = NomeNormSel
			            )
			        )
			    )
			
			VAR CoordCtx = SELECTEDVALUE(Eixo_Colaboradores[Coordenador])
			VAR LiderCtx = SELECTEDVALUE(Eixo_Colaboradores[Líder])
			VAR PoloCtx  = SELECTEDVALUE(Eixo_Colaboradores[Polo Base (Regra)])
			
			RETURN
			IF(
			    NOT IsLinha,
			    IF(
			        NOT ISBLANK(PoloCtx) && PoloCtx <> "" && PoloCtx <> "Matriz",
			        CALCULATE(
			            [SLA_% Base],
			            REMOVEFILTERS(Eixo_Colaboradores),
			            REMOVEFILTERS(FactOS[Matricula]),
			            TREATAS({ PoloCtx }, FactOS[des_service_provider])
			        ),
			        IF(
			            NOT ISBLANK(LiderCtx) && LiderCtx <> "" && LiderCtx <> "Matriz",
			            CALCULATE(
			                [SLA_% Base],
			                REMOVEFILTERS(Eixo_Colaboradores),
			                REMOVEFILTERS(FactOS[Matricula]),
			                TREATAS({ LiderCtx }, FactOS[Líder])
			            ),
			            IF(
			                NOT ISBLANK(CoordCtx) && CoordCtx <> "" && CoordCtx <> "Matriz",
			                CALCULATE(
			                    [SLA_% Base],
			                    REMOVEFILTERS(Eixo_Colaboradores),
			                    REMOVEFILTERS(FactOS[Matricula]),
			                    TREATAS({ CoordCtx }, FactOS[Coordenador.Coordenador])
			                ),
			                CALCULATE(
			                    [SLA_% Base],
			                    REMOVEFILTERS(Eixo_Colaboradores),
			                    REMOVEFILTERS(FactOS[Matricula]),
			                    REMOVEFILTERS(FactOS[des_service_provider])
			                )
			            )
			        )
			    ),
			    SWITCH(
			        TRUE(),
			        IsMatrizSel,
			            CALCULATE(
			                [SLA_% Base],
			                REMOVEFILTERS(Eixo_Colaboradores),
			                REMOVEFILTERS(FactOS[Matricula]),
			                REMOVEFILTERS(FactOS[des_service_provider])
			            ),
			
			        CONTAINSSTRING(CargoSelNorm, "TECNICO") && NOT ISBLANK(MatriculaSel),
			            CALCULATE(
			                [SLA_% Base],
			                KEEPFILTERS(
			                    FILTER(
			                        ALL(FactOS),
			                        FORMAT(FactOS[Matricula], "") = MatSelTxt
			                    )
			                )
			            ),
			
			        CONTAINSSTRING(CargoSelNorm, "ASSISTENTE") && NOT ISBLANK(PoloRegra),
			            CALCULATE(
			                [SLA_% Base],
			                REMOVEFILTERS(Eixo_Colaboradores),
			                REMOVEFILTERS(FactOS[Matricula]),
			                REMOVEFILTERS(FactOS[des_service_provider]),
			                TREATAS({ PoloRegra }, FactOS[des_service_provider])
			            ),
			
			        CONTAINSSTRING(CargoSelNorm, "LIDER") && NOT ISEMPTY(Polos_Lider),
			            CALCULATE(
			                [SLA_% Base],
			                REMOVEFILTERS(Eixo_Colaboradores),
			                REMOVEFILTERS(FactOS[Matricula]),
			                TREATAS(Polos_Lider, FactOS[des_service_provider])
			            ),
			        CONTAINSSTRING(CargoSelNorm, "COORDENADOR") && NOT ISEMPTY(Polos_Coord),
			            CALCULATE(
			                [SLA_% Base],
			                REMOVEFILTERS(Eixo_Colaboradores),
			                REMOVEFILTERS(FactOS[Matricula]),
			                TREATAS(Polos_Coord, FactOS[des_service_provider])
			            ),
			
			        [SLA_% Base]
			    )
			)
		lineageTag: 29de8243-83e4-47bc-920d-448890802d57

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Ativacao_% (Regra Cargo)' =
			
			VAR CargoSel     = SELECTEDVALUE(Eixo_Colaboradores[Cargo])
			VAR CargoSelNorm0= UPPER(TRIM(CargoSel))
			VAR CargoSelNorm =
			    SUBSTITUTE(
			    SUBSTITUTE(
			    SUBSTITUTE(
			    SUBSTITUTE(
			    SUBSTITUTE(
			    SUBSTITUTE(
			    SUBSTITUTE(
			    SUBSTITUTE(
			    SUBSTITUTE(
			    SUBSTITUTE(
			    SUBSTITUTE(
			    SUBSTITUTE(CargoSelNorm0,"Á","A"),"À","A"),"Â","A"),"Ã","A"),"É","E"),
			    "Ê","E"),"Í","I"),"Ó","O"),"Ô","O"),"Õ","O"),"Ú","U"),"Ü","U")
			VAR PoloRegra    = SELECTEDVALUE(Eixo_Colaboradores[Polo Base (Regra)])
			VAR MatriculaSel = SELECTEDVALUE(Eixo_Colaboradores[Matricula])
			VAR MatSelTxt    = FORMAT(MatriculaSel, "")
			VAR NomeNormSel  = SELECTEDVALUE(Eixo_Colaboradores[Nome_Normalizado])
			VAR IsMatrizSel  = COALESCE(SELECTEDVALUE(Eixo_Colaboradores[IsMatriz]), FALSE())
			
			VAR IsLinha =
			    HASONEVALUE(Eixo_Colaboradores[Nome_Normalizado]) ||
			    HASONEVALUE(Eixo_Colaboradores[Matricula])
			
			VAR Polos_Lider =
			    CALCULATETABLE(
			        DISTINCT(FactOS[des_service_provider]),
			        KEEPFILTERS(
			            FILTER(
			                ALL(FactOS[Líder]),
			                VAR n  = UPPER(TRIM(FactOS[Líder]))
			                VAR n1 = SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(n,
			                       "Á","A"),"À","A"),"Â","A"),"Ã","A"),"É","E"),"Ê","E"),"Í","I"),"Ó","O"),"Ô","O"),"Õ","O")
			                VAR n2 = SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(n1,"Ú","U"),"Ü","U"),"Ç","C")
			                RETURN n2 = NomeNormSel
			            )
			        )
			    )
			VAR Polos_Coord =
			    CALCULATETABLE(
			        DISTINCT(FactOS[des_service_provider]),
			        KEEPFILTERS(
			            FILTER(
			                ALL(FactOS[Coordenador.Coordenador]),
			                VAR n  = UPPER(TRIM(FactOS[Coordenador.Coordenador]))
			                VAR n1 = SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(n,
			                       "Á","A"),"À","A"),"Â","A"),"Ã","A"),"É","E"),"Ê","E"),"Í","I"),"Ó","O"),"Ô","O"),"Õ","O")
			                VAR n2 = SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(n1,"Ú","U"),"Ü","U"),"Ç","C")
			                RETURN n2 = NomeNormSel
			            )
			        )
			    )
			
			VAR CoordCtx = SELECTEDVALUE(Eixo_Colaboradores[Coordenador])
			VAR LiderCtx = SELECTEDVALUE(Eixo_Colaboradores[Líder])
			VAR PoloCtx  = SELECTEDVALUE(Eixo_Colaboradores[Polo Base (Regra)])
			
			RETURN
			IF(
			    NOT IsLinha,
			    IF(
			        NOT ISBLANK(PoloCtx) && PoloCtx <> "" && PoloCtx <> "Matriz",
			        CALCULATE(
			            [Ativacao_% Base],
			            REMOVEFILTERS(Eixo_Colaboradores),
			            REMOVEFILTERS(FactOS[Matricula]),
			            TREATAS({ PoloCtx }, FactOS[des_service_provider])
			        ),
			        IF(
			            NOT ISBLANK(LiderCtx) && LiderCtx <> "" && LiderCtx <> "Matriz",
			            CALCULATE(
			                [Ativacao_% Base],
			                REMOVEFILTERS(Eixo_Colaboradores),
			                REMOVEFILTERS(FactOS[Matricula]),
			                TREATAS({ LiderCtx }, FactOS[Líder])
			            ),
			            IF(
			                NOT ISBLANK(CoordCtx) && CoordCtx <> "" && CoordCtx <> "Matriz",
			                CALCULATE(
			                    [Ativacao_% Base],
			                    REMOVEFILTERS(Eixo_Colaboradores),
			                    REMOVEFILTERS(FactOS[Matricula]),
			                    TREATAS({ CoordCtx }, FactOS[Coordenador.Coordenador])
			                ),
			                CALCULATE(
			                    [Ativacao_% Base],
			                    REMOVEFILTERS(Eixo_Colaboradores),
			                    REMOVEFILTERS(FactOS[Matricula]),
			                    REMOVEFILTERS(FactOS[des_service_provider])
			                )
			            )
			        )
			    ),
			    SWITCH(
			        TRUE(),
			        IsMatrizSel,
			            CALCULATE(
			                [Ativacao_% Base],
			                REMOVEFILTERS(Eixo_Colaboradores),
			                REMOVEFILTERS(FactOS[Matricula]),
			                REMOVEFILTERS(FactOS[des_service_provider])
			            ),
			
			        CONTAINSSTRING(CargoSelNorm, "TECNICO") && NOT ISBLANK(MatriculaSel),
			            CALCULATE(
			                [Ativacao_% Base],
			                KEEPFILTERS(
			                    FILTER(
			                        ALL(FactOS),
			                        FORMAT(FactOS[Matricula], "") = MatSelTxt
			                    )
			                )
			            ),
			
			        CONTAINSSTRING(CargoSelNorm, "ASSISTENTE") && NOT ISBLANK(PoloRegra),
			            CALCULATE(
			                [Ativacao_% Base],
			                REMOVEFILTERS(Eixo_Colaboradores),
			                REMOVEFILTERS(FactOS[Matricula]),
			                REMOVEFILTERS(FactOS[des_service_provider]),
			                TREATAS({ PoloRegra }, FactOS[des_service_provider])
			            ),
			
			        CONTAINSSTRING(CargoSelNorm, "LIDER") && NOT ISEMPTY(Polos_Lider),
			            CALCULATE(
			                [Ativacao_% Base],
			                REMOVEFILTERS(Eixo_Colaboradores),
			                REMOVEFILTERS(FactOS[Matricula]),
			                TREATAS(Polos_Lider, FactOS[des_service_provider])
			            ),
			        CONTAINSSTRING(CargoSelNorm, "COORDENADOR") && NOT ISEMPTY(Polos_Coord),
			            CALCULATE(
			                [Ativacao_% Base],
			                REMOVEFILTERS(Eixo_Colaboradores),
			                REMOVEFILTERS(FactOS[Matricula]),
			                TREATAS(Polos_Coord, FactOS[des_service_provider])
			            ),
			
			        [Ativacao_% Base]
			    )
			)
		lineageTag: 3e64dbab-afa6-4caf-86e4-af0801a8a852

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'CSAT Médio (Regra Cargo)' =
			
			VAR CargoSel     = SELECTEDVALUE(Eixo_Colaboradores[Cargo])
			VAR CargoSelNorm0= UPPER(TRIM(CargoSel))
			VAR CargoSelNorm =
			    SUBSTITUTE(
			    SUBSTITUTE(
			    SUBSTITUTE(
			    SUBSTITUTE(
			    SUBSTITUTE(
			    SUBSTITUTE(
			    SUBSTITUTE(
			    SUBSTITUTE(
			    SUBSTITUTE(
			    SUBSTITUTE(
			    SUBSTITUTE(
			    SUBSTITUTE(CargoSelNorm0,"Á","A"),"À","A"),"Â","A"),"Ã","A"),"É","E"),
			    "Ê","E"),"Í","I"),"Ó","O"),"Ô","O"),"Õ","O"),"Ú","U"),"Ü","U")
			VAR PoloRegra    = SELECTEDVALUE(Eixo_Colaboradores[Polo Base (Regra)])
			VAR MatriculaSel = SELECTEDVALUE(Eixo_Colaboradores[Matricula])
			VAR MatSelTxt    = FORMAT(MatriculaSel, "")
			VAR NomeNormSel  = SELECTEDVALUE(Eixo_Colaboradores[Nome_Normalizado])
			VAR IsMatrizSel  = COALESCE(SELECTEDVALUE(Eixo_Colaboradores[IsMatriz]), FALSE())
			
			VAR IsLinha =
			    HASONEVALUE(Eixo_Colaboradores[Nome_Normalizado]) ||
			    HASONEVALUE(Eixo_Colaboradores[Matricula])
			
			VAR FiltroSlicerHierarquia =
			    TREATAS(VALUES(DimHierarquiaSlicer[KeyHierarquia]), FactCSAT[KeyHierarquia])
			
			VAR Polos_Lider =
			    CALCULATETABLE(
			        DISTINCT(FactOS[des_service_provider]),
			        KEEPFILTERS(
			            FILTER(
			                ALL(FactOS[Líder]),
			                VAR n  = UPPER(TRIM(FactOS[Líder]))
			                VAR n1 = SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(n,
			                       "Á","A"),"À","A"),"Â","A"),"Ã","A"),"É","E"),"Ê","E"),"Í","I"),"Ó","O"),"Ô","O"),"Õ","O")
			                VAR n2 = SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(n1,"Ú","U"),"Ü","U"),"Ç","C")
			                RETURN n2 = NomeNormSel
			            )
			        )
			    )
			VAR Polos_Coord =
			    CALCULATETABLE(
			        DISTINCT(FactOS[des_service_provider]),
			        KEEPFILTERS(
			            FILTER(
			                ALL(FactOS[Coordenador.Coordenador]),
			                VAR n  = UPPER(TRIM(FactOS[Coordenador.Coordenador]))
			                VAR n1 = SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(n,
			                       "Á","A"),"À","A"),"Â","A"),"Ã","A"),"É","E"),"Ê","E"),"Í","I"),"Ó","O"),"Ô","O"),"Õ","O")
			                VAR n2 = SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(n1,"Ú","U"),"Ü","U"),"Ç","C")
			                RETURN n2 = NomeNormSel
			            )
			        )
			    )
			
			VAR CoordCtx = SELECTEDVALUE(Eixo_Colaboradores[Coordenador])
			VAR LiderCtx = SELECTEDVALUE(Eixo_Colaboradores[Líder])
			VAR PoloCtx  = SELECTEDVALUE(Eixo_Colaboradores[Polo Base (Regra)])
			
			RETURN
			IF(
			    NOT IsLinha,
			    IF(
			        NOT ISBLANK(PoloCtx) && PoloCtx <> "" && PoloCtx <> "Matriz",
			        CALCULATE(
			            [CSAT Médio Base (Considerar)],
			            REMOVEFILTERS(Eixo_Colaboradores),
			            REMOVEFILTERS(FactCSAT[Matricula2]),
			            REMOVEFILTERS(FactCSAT[des_service_provider]),
			            TREATAS({ PoloCtx }, FactCSAT[des_service_provider]),
			            KEEPFILTERS(FiltroSlicerHierarquia)
			        ),
			        IF(
			            NOT ISBLANK(LiderCtx) && LiderCtx <> "" && LiderCtx <> "Matriz",
			            CALCULATE(
			                [CSAT Médio Base (Considerar)],
			                REMOVEFILTERS(Eixo_Colaboradores),
			                REMOVEFILTERS(FactCSAT[Matricula2]),
			                REMOVEFILTERS(FactCSAT[des_service_provider]),
			                TREATAS({ LiderCtx }, FactCSAT[Líder]),
			                KEEPFILTERS(FiltroSlicerHierarquia)
			            ),
			            IF(
			                NOT ISBLANK(CoordCtx) && CoordCtx <> "" && CoordCtx <> "Matriz",
			                CALCULATE(
			                    [CSAT Médio Base (Considerar)],
			                    REMOVEFILTERS(Eixo_Colaboradores),
			                    REMOVEFILTERS(FactCSAT[Matricula2]),
			                    REMOVEFILTERS(FactCSAT[des_service_provider]),
			                    TREATAS({ CoordCtx }, FactCSAT[Coordenador]),
			                    KEEPFILTERS(FiltroSlicerHierarquia)
			                ),
			                CALCULATE(
			                    [CSAT Médio Base (Considerar)],
			                    REMOVEFILTERS(Eixo_Colaboradores),
			                    REMOVEFILTERS(FactCSAT[Matricula2]),
			                    REMOVEFILTERS(FactCSAT[des_service_provider]),
			                    KEEPFILTERS(FiltroSlicerHierarquia)
			                )
			            )
			        )
			    ),
			    SWITCH(
			        TRUE(),
			        IsMatrizSel,
			            CALCULATE(
			                [CSAT Médio Base (Considerar)],
			                REMOVEFILTERS(Eixo_Colaboradores),
			                REMOVEFILTERS(FactCSAT[Matricula2]),
			                REMOVEFILTERS(FactCSAT[des_service_provider]),
			                KEEPFILTERS(FiltroSlicerHierarquia)
			            ),
			
			        CONTAINSSTRING(CargoSelNorm, "TECNICO") && NOT ISBLANK(MatriculaSel),
			            CALCULATE(
			                [CSAT Médio Base (Considerar)],
			                KEEPFILTERS(FactCSAT[STATUS] = "Considerar"),
			                KEEPFILTERS(
			                    FILTER(
			                        ALL(FactCSAT),
			                        FORMAT(FactCSAT[Matricula2], "") = MatSelTxt
			                    )
			                ),
			                KEEPFILTERS(FiltroSlicerHierarquia)
			            ),
			
			        CONTAINSSTRING(CargoSelNorm, "ASSISTENTE") && NOT ISBLANK(PoloRegra),
			            CALCULATE(
			                [CSAT Médio Base (Considerar)],
			                REMOVEFILTERS(Eixo_Colaboradores),
			                REMOVEFILTERS(FactCSAT[Matricula2]),
			                REMOVEFILTERS(FactCSAT[des_service_provider]),
			                TREATAS({ PoloRegra }, FactCSAT[des_service_provider]),
			                KEEPFILTERS(FiltroSlicerHierarquia)
			            ),
			
			        CONTAINSSTRING(CargoSelNorm, "LIDER") && NOT ISEMPTY(Polos_Lider),
			            CALCULATE(
			                [CSAT Médio Base (Considerar)],
			                REMOVEFILTERS(Eixo_Colaboradores),
			                REMOVEFILTERS(FactCSAT[Matricula2]),
			                TREATAS(Polos_Lider, FactCSAT[des_service_provider]),
			                KEEPFILTERS(FiltroSlicerHierarquia)
			            ),
			        CONTAINSSTRING(CargoSelNorm, "COORDENADOR") && NOT ISEMPTY(Polos_Coord),
			            CALCULATE(
			                [CSAT Médio Base (Considerar)],
			                REMOVEFILTERS(Eixo_Colaboradores),
			                REMOVEFILTERS(FactCSAT[Matricula2]),
			                TREATAS(Polos_Coord, FactCSAT[des_service_provider]),
			                KEEPFILTERS(FiltroSlicerHierarquia)
			            ),
			
			        CALCULATE(
			            [CSAT Médio Base (Considerar)],
			            KEEPFILTERS(FiltroSlicerHierarquia)
			        )
			    )
			)
		lineageTag: 7d12b9ca-6216-4221-9ac3-978ee88fd224

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'DEBUG – Técnico 03/04 (contagem)' =
			
			VAR MatSelTxt = FORMAT(SELECTEDVALUE(Eixo_Colaboradores[Matricula]), "")
			VAR OS_rows =
			    CALCULATE(
			        COUNTROWS(FactOS),
			        KEEPFILTERS( FILTER(ALL(FactOS), FORMAT(FactOS[Matricula], "") = MatSelTxt) )
			    )
			VAR CSAT_rows =
			    CALCULATE(
			        COUNTROWS(FactCSAT),
			        KEEPFILTERS(FactCSAT[STATUS] = "Considerar"),
			        KEEPFILTERS( FILTER(ALL(FactCSAT), FORMAT(FactCSAT[Matricula2], "") = MatSelTxt) )
			    )
			RETURN "OS=" & OS_rows & " | CSAT=" & CSAT_rows
		lineageTag: 04ad3cdd-b2f2-4929-ac16-d2a73d75a382

	column des_service_provider
		dataType: string
		lineageTag: da102112-e565-4ac9-ac4d-d9d8f26de373
		summarizeBy: none
		sourceColumn: des_service_provider

		annotation SummarizationSetBy = Automatic

	column des_closed_by_user
		dataType: string
		lineageTag: c27b5782-1b03-4fdc-9327-d41c4edad23a
		summarizeBy: none
		sourceColumn: des_closed_by_user

		annotation SummarizationSetBy = Automatic

	column cod_service_order
		dataType: string
		lineageTag: 41cfb8d0-fdbf-4646-a315-4d666360bfad
		summarizeBy: none
		sourceColumn: cod_service_order

		annotation SummarizationSetBy = Automatic

	column cidade
		dataType: string
		lineageTag: c1ec12d6-d777-4348-bca6-ac36061370c0
		summarizeBy: none
		sourceColumn: cidade

		annotation SummarizationSetBy = Automatic

	column serial_novo
		dataType: string
		lineageTag: 94bd264b-b6a6-4661-bb54-d679f7a624a8
		summarizeBy: none
		sourceColumn: serial_novo

		annotation SummarizationSetBy = Automatic

	column novo_equipamento
		dataType: string
		lineageTag: fa363e77-8568-416d-841d-6b8c45a582f6
		summarizeBy: none
		sourceColumn: novo_equipamento

		annotation SummarizationSetBy = Automatic

	column motivo_saida
		dataType: string
		lineageTag: 50eba23f-ff3b-4863-9444-15f52d6fcf3d
		summarizeBy: none
		sourceColumn: motivo_saida

		annotation SummarizationSetBy = Automatic

	column qtd_ordens
		dataType: int64
		formatString: 0
		lineageTag: 7855e929-cd57-4b92-a6e9-b049b72538d6
		summarizeBy: sum
		sourceColumn: qtd_ordens

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

	column qtd_ordens_dentro_do_prazo_calculado
		dataType: string
		lineageTag: 2bf3bb0c-8155-43b2-8546-d1a6ec9bf2a7
		summarizeBy: none
		sourceColumn: qtd_ordens_dentro_do_prazo_calculado

		annotation SummarizationSetBy = Automatic

	column pct_ordens_dentro_do_prazo_calculado
		dataType: int64
		formatString: 0%;-0%;0%
		lineageTag: f8aa05de-6783-4db0-8e31-6955e7f8b938
		summarizeBy: sum
		sourceColumn: pct_ordens_dentro_do_prazo_calculado

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

	column qtd_ativacoes
		dataType: string
		lineageTag: c95aae0b-8d0d-411b-8f6e-2c7e0cfa4d33
		summarizeBy: none
		sourceColumn: qtd_ativacoes

		annotation SummarizationSetBy = Automatic

	column pct_ordens_com_ativacao
		dataType: int64
		formatString: 0%;-0%;0%
		lineageTag: 730b5a89-ceae-4d6f-b8d7-21ca25e06092
		summarizeBy: sum
		sourceColumn: pct_ordens_com_ativacao

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

	column data_abertura
		dataType: string
		lineageTag: 1d1528e9-2a2b-45c1-97da-5dde880101d3
		summarizeBy: none
		sourceColumn: data_abertura

		annotation SummarizationSetBy = Automatic

	column data_limite
		dataType: string
		lineageTag: 7fdf26f1-4d81-4f3a-9403-2e6ab8c374aa
		summarizeBy: none
		sourceColumn: data_limite

		annotation SummarizationSetBy = Automatic

	column data_fechamento
		dataType: string
		lineageTag: 5060fb35-b4b7-4abc-9030-7bc7f1551868
		summarizeBy: none
		sourceColumn: data_fechamento

		annotation SummarizationSetBy = Automatic

	column diferenca_sla_horas_fechamento
		dataType: string
		lineageTag: 7c9de796-380c-464b-8ef9-63bff0235734
		summarizeBy: none
		sourceColumn: diferenca_sla_horas_fechamento

		annotation SummarizationSetBy = Automatic

	column status_dentro_fora_prazo
		dataType: string
		lineageTag: 0e73875d-eb6c-494a-b9a6-68d1e2313698
		summarizeBy: none
		sourceColumn: status_dentro_fora_prazo

		annotation SummarizationSetBy = Automatic

	column 'Data Ativação'
		dataType: string
		lineageTag: 9c091430-9840-45d5-868f-a070affe05b9
		summarizeBy: none
		sourceColumn: Data Ativação

		annotation SummarizationSetBy = Automatic

	column 'Codigo Polo'
		dataType: string
		lineageTag: 48f6d5f9-045d-4044-91cf-e1e8e6194ef7
		summarizeBy: none
		sourceColumn: Codigo Polo

		annotation SummarizationSetBy = Automatic

	column 'Coordenador.Coordenador'
		dataType: string
		lineageTag: b477b345-08df-480c-abb0-26bd393874b0
		summarizeBy: none
		sourceColumn: Coordenador.Coordenador

		annotation SummarizationSetBy = Automatic

	column Líder
		dataType: string
		lineageTag: 2ea3f967-624c-4a60-835e-1a1c4785acd2
		summarizeBy: none
		sourceColumn: Líder

		annotation SummarizationSetBy = Automatic

	column Matricula
		dataType: string
		lineageTag: 6ab5c8d3-310a-4944-a312-20592bb120a2
		summarizeBy: none
		sourceColumn: Matricula

		annotation SummarizationSetBy = Automatic

	column SLA_Dentro_Prazo
		dataType: int64
		formatString: 0
		lineageTag: d2b7708d-27e2-46e0-93fc-6b7dbfac644a
		summarizeBy: sum
		sourceColumn: SLA_Dentro_Prazo

		annotation SummarizationSetBy = Automatic

	column Ativacao_Flag
		dataType: int64
		formatString: 0
		lineageTag: ac67b447-fa8d-436c-a246-e384ce367f35
		summarizeBy: sum
		sourceColumn: Ativacao_Flag

		annotation SummarizationSetBy = Automatic

	column KeyHierarquia =
			
			VAR Coord = COALESCE( TRIM( FactOS[Coordenador.Coordenador] ), "" )
			VAR Lider = COALESCE( TRIM( FactOS[Líder] ), "" )
			VAR Polo  = COALESCE( TRIM( FactOS[des_service_provider] ), "" )
			RETURN Coord & "|" & Lider & "|" & Polo
		lineageTag: e644a80d-5342-4691-9dd0-c942348c9109
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'JUSTIFICATIVA ATIVAÇÃO'
		dataType: string
		lineageTag: 191beb76-ab91-44a7-966e-04b4d39cc5b8
		summarizeBy: none
		sourceColumn: JUSTIFICATIVA ATIVAÇÃO

		annotation SummarizationSetBy = Automatic

	column ATIVO
		dataType: string
		lineageTag: 9486a6ca-c1bd-469e-acec-b5b4eb0feacf
		summarizeBy: none
		sourceColumn: ATIVO

		annotation SummarizationSetBy = Automatic

	column ATIVAÇÃO
		dataType: string
		lineageTag: 584d7f43-60da-4a1d-8d12-6cc8a0c3275f
		summarizeBy: none
		sourceColumn: ATIVAÇÃO

		annotation SummarizationSetBy = Automatic

	column JUSTIFICATIVA
		dataType: string
		lineageTag: dda7e4b2-af73-4d9c-ad12-75f4af92a88c
		summarizeBy: none
		sourceColumn: JUSTIFICATIVA

		annotation SummarizationSetBy = Automatic

	column OBSERVAÇÂO
		dataType: string
		lineageTag: 5ce989f8-4cf5-41c6-b475-82fc2d8d8b56
		summarizeBy: none
		sourceColumn: OBSERVAÇÂO

		annotation SummarizationSetBy = Automatic

	column 'FINAL JUSTIFICATIVA'
		dataType: string
		lineageTag: 00e25954-8279-481d-af99-beaea0236557
		summarizeBy: none
		sourceColumn: FINAL JUSTIFICATIVA

		annotation SummarizationSetBy = Automatic

	column REVISITA
		dataType: string
		lineageTag: 5f026ddc-2e9d-4142-883b-6d106cdc0ebc
		summarizeBy: none
		sourceColumn: REVISITA

		annotation SummarizationSetBy = Automatic

	column 'REVISITA DENTRO?'
		dataType: string
		lineageTag: 556146b7-1dcf-41f3-bc44-8558f80f4818
		summarizeBy: none
		sourceColumn: REVISITA DENTRO?

		annotation SummarizationSetBy = Automatic

	partition FactOS = m
		mode: import
		source =
				let
				    Fonte = Excel.Workbook(
				        File.Contents("C:\Users\sbahia\OneDrive - UNIVERSO ONLINE S.A\Área de Trabalho\Ambiente PY\logins\Dash Fifo\AUT RV\RV_JANEIRO26\Dados_RV_Janeiro_2026_1.xlsx"),
				        null,
				        false
				    ),
				
				    Base03_Sheet = Fonte{[Item="03 - Dados_Dentro_Fora_Ativação", Kind="Sheet"]}[Data],
				    Cabecalhos = Table.PromoteHeaders(Base03_Sheet, [PromoteAllScalars=true]),
				
				    // Limpa #N/A/#N/A! em todas as colunas
				    LimpaNA1 = Table.ReplaceValue(Cabecalhos, "#N/A", null, Replacer.ReplaceValue, Table.ColumnNames(Cabecalhos)),
				    LimpaNA2 = Table.ReplaceValue(LimpaNA1, "#N/A!", null, Replacer.ReplaceValue, Table.ColumnNames(LimpaNA1)),
				
				    // Normaliza Matricula (não filtramos nulos aqui para não perder eventos do polo)
				    NormalizaMatricula = Table.TransformColumns(
				        LimpaNA2,
				        {{"Matricula", each try Text.Clean(Text.Trim(Text.From(_))) otherwise null, type text}}
				    ),
				
				    // Padroniza 'des_service_provider' (se já existir, mantém; senão renomeia de 'Polo' ou 'Codigo_Polo'; senão cria nulo)
				    Colunas = Table.ColumnNames(NormalizaMatricula),
				    GaranteDSP =
				        if List.Contains(Colunas, "des_service_provider") then
				            NormalizaMatricula
				        else if List.Contains(Colunas, "Polo") then
				            Table.RenameColumns(NormalizaMatricula, {{"Polo", "des_service_provider"}})
				        else if List.Contains(Colunas, "Codigo_Polo") then
				            Table.RenameColumns(NormalizaMatricula, {{"Codigo_Polo", "des_service_provider"}})
				        else
				            Table.AddColumn(NormalizaMatricula, "des_service_provider", each null, type text),
				
				    LimpaDSP = Table.TransformColumns(
				        GaranteDSP,
				        {{"des_service_provider", each if _ = null then null else Text.Clean(Text.Trim(Text.From(_))), type text}}
				    ),
				
				    // Cria SLA_Dentro_Prazo (1/0) a partir de colunas alternativas
				    AddSLA = Table.AddColumn(
				        LimpaDSP,
				        "SLA_Dentro_Prazo",
				        each
				            let
				                cols = Table.ColumnNames(LimpaDSP),
				                cand = {"Está no Prazo?", "Dentro do Prazo", "SLA"},
				                colName =
				                    if List.Contains(cols, "Está no Prazo?") then "Está no Prazo?"
				                    else if List.Contains(cols, "Dentro do Prazo") then "Dentro do Prazo"
				                    else if List.Contains(cols, "SLA") then "SLA"
				                    else null,
				                raw = if colName = null then null else Record.Field(_, colName),
				                txt = if raw = null then null else Text.Upper(Text.Trim(Text.From(raw))),
				                flag =
				                    if raw = null then null
				                    else if Value.Is(raw, Int64.Type) or Value.Is(raw, Number.Type) then (if Number.From(raw) <> 0 then 1 else 0)
				                    else if List.Contains({"SIM","S","TRUE","DENTRO","DENTRO DO PRAZO","OK","YES","Y","1"}, txt) then 1
				                    else if List.Contains({"NÃO","NAO","N","FALSE","FORA","FORA DO PRAZO","NO","0"}, txt) then 0
				                    else null
				            in
				                flag,
				        Int64.Type
				    ),
				
				    // Cria Ativacao_Flag (1/0) a partir de "Ativação" ou "Ativacao"
				    AddAtivacao = Table.AddColumn(
				        AddSLA,
				        "Ativacao_Flag",
				        each
				            let
				                cols = Table.ColumnNames(AddSLA),
				                colName = if List.Contains(cols, "Ativação") then "Ativação" else if List.Contains(cols, "Ativacao") then "Ativacao" else null,
				                raw = if colName = null then null else Record.Field(_, colName),
				                txt = if raw = null then null else Text.Upper(Text.Trim(Text.From(raw))),
				                flag =
				                    if raw = null then null
				                    else if Value.Is(raw, Int64.Type) or Value.Is(raw, Number.Type) then (if Number.From(raw) <> 0 then 1 else 0)
				                    else if List.Contains({"SIM","S","TRUE","OK","YES","Y","1"}, txt) then 1
				                    else if List.Contains({"NÃO","NAO","N","FALSE","NO","0"}, txt) then 0
				                    else null
				            in
				                flag,
				        Int64.Type
				    ),
				    #"Linhas Filtradas" = Table.SelectRows(AddAtivacao, each ([motivo_saida] <> "visita técnica"))
				in
				    #"Linhas Filtradas"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

